# This is a basic workflow to help you get started with Actions

name: CI - TEST

on:
  push:
    branches: [test]
  # pull_request:
  #   branches: [stage]

jobs:
  front-end:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: Install firebase tools
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
        env:
          CI: true
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.TEST_REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_DATABASE_URL: ${{ secrets.TEST_REACT_APP_FIREBASE_DATABASE_URL }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.TEST_REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.TEST_REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.TEST_REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.TEST_REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.TEST_REACT_APP_FIREBASE_APP_ID }}
          REACT_APP_JITSI_ROOM_PREFIX: test
          REACT_APP_ENV: TEST
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.STAGE_REACT_APP_GOOGLE_MAPS_API_KEY }}

      - name: Deploy hosting
        run: |
          firebase use --token ${{ secrets.STAGE_FIREBASE_DEPLOY_KEY }} ${{ secrets.TEST_REACT_APP_FIREBASE_PROJECT_ID }}
          firebase deploy -m "Deployed from github actions (${{ github.run_id }}) by ${{ github.actor }}" --token ${{ secrets.STAGE_FIREBASE_DEPLOY_KEY }} --only hosting

  functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: Install firebase tools
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install
        working-directory: ./functions

      - name: Select firebase project
        run: firebase use --token ${{ secrets.STAGE_FIREBASE_DEPLOY_KEY }} ${{ secrets.TEST_REACT_APP_FIREBASE_PROJECT_ID }}

      - name: Set firebase config
        run: firebase  --token ${{ secrets.STAGE_FIREBASE_DEPLOY_KEY }} functions:config:set global.base_url="${{ secrets.TEST_REACT_APP_FIREBASE_BASE_URL }}" slack.webhook="${{ secrets.TEST_SLACK_WEBHOOK }}" sendgrid.key="${{ secrets.TEST_SENDGRID_KEY }}"

      - name: Deploy functions
        run: firebase deploy --token ${{ secrets.STAGE_FIREBASE_DEPLOY_KEY }} --only functions
